name: Tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install test dependencies
        run: |
          pip install setuptools --upgrade
          pip install .[test]
      - name: Run unit tests
        working-directory: genswaptrades/
        run: pytest -v tests/tests.py